import type { RuleDefinition } from '../../types'

export const MERISE_SOURCE = { label: 'Cours MERISE · Université Paris-Saclay', url: 'https://www.imo.universite-paris-saclay.fr/~benjamin.auder/teachings/bdd/s1_cours.html' }
export const ASSOCIATION_SOURCE = { label: 'Associations · Université de Strasbourg', url: 'https://colibri.unistra.fr/fr/course/practice/concevoir-une-base-de-donnees/creer-un-modele-conceptuel/3646' }
export const SQL_SOURCE = { label: 'Contraintes · PostgreSQL', url: 'https://www.postgresql.org/docs/current/ddl-constraints.html' }

/** Stable IDs are persisted by the ignore system. Keep checks separate from their presentation. */
export const ADVANCED_RULES = {
  E013: { id: 'MERISE-E013', severity: 'error', title: 'ID interne vide ou dupliqué', category: 'model', certainty: 'certain', explanation: 'Deux objets partagent une référence technique, ou une référence est vide.', suggestion: 'Recréez l’objet concerné ou corrigez ses ID et références dans le fichier importé.' },
  E014: { id: 'MERISE-E014', severity: 'error', title: 'Identifiant principal ambigu ou absent', category: 'model', certainty: 'certain', explanation: 'L’export exige un seul identifiant principal parmi les identifiants déclarés.', suggestion: 'Choisissez un identifiant principal ; conservez les autres comme clés alternatives.', source: SQL_SOURCE },
  E015: { id: 'MERISE-E015', severity: 'error', title: 'Propriété identifiante nullable', category: 'model', certainty: 'certain', explanation: 'Une composante d’un identifiant ne peut pas être absente.', suggestion: 'Rendez chaque composante de cet identifiant obligatoire (NOT NULL).', source: MERISE_SOURCE },
  E016: { id: 'MERISE-E016', severity: 'error', title: 'Configuration de type invalide', category: 'export', certainty: 'certain', explanation: 'La configuration détaillée du type ne peut pas être convertie en SQL.', suggestion: 'Ouvrez la propriété et corrigez sa famille, longueur, précision ou son type libre.' },
  E017: { id: 'MERISE-E017', severity: 'error', title: 'Famille de type incohérente', category: 'model', certainty: 'certain', explanation: 'Le type conceptuel et sa configuration détaillée désignent des familles différentes.', suggestion: 'Resélectionnez le type dans le formulaire de propriété pour synchroniser les deux valeurs.' },
  E018: { id: 'MERISE-E018', severity: 'error', title: 'Collision de colonnes SQL', category: 'export', certainty: 'certain', explanation: 'Plusieurs colonnes produisent le même nom physique, y compris après migration des associations.', suggestion: 'Distinguez les noms concernés, leurs accents, séparateurs ou préfixes avant 63 caractères.' },
  E019: { id: 'MERISE-E019', severity: 'error', title: 'Référence SQL invalide', category: 'export', certainty: 'certain', explanation: 'Une clé étrangère générée ne référence pas une colonne primaire existante et de même type.', suggestion: 'Vérifiez les identifiants des entités et les collisions avec les propriétés migrées.', source: SQL_SOURCE },
  W006: { id: 'MERISE-W006', severity: 'warning', title: 'Identifiant redondant ou non minimal', category: 'normalization', certainty: 'certain', explanation: 'Un identifiant contient une clé déjà unique, ou répète un autre identifiant.', suggestion: 'Conservez les clés candidates minimales ; un index métier supplémentaire n’est pas forcément un identifiant.', source: MERISE_SOURCE },
  W007: { id: 'MERISE-W007', severity: 'warning', title: 'Rôles réflexifs ambigus', category: 'model', certainty: 'heuristic', explanation: 'Plusieurs participations de la même entité ont un rôle vide ou identique.', suggestion: 'Nommez les rôles (parent/enfant, émetteur/destinataire), sauf relation volontairement symétrique.', source: MERISE_SOURCE },
  W008: { id: 'MERISE-W008', severity: 'warning', title: 'Association potentiellement dupliquée', category: 'normalization', certainty: 'heuristic', explanation: 'Même nom, mêmes participants, mêmes rôles et mêmes cardinalités : vérifiez si ces liens sont distincts.', suggestion: 'Fusionnez un doublon réel ou précisez les noms et rôles métier. Plusieurs associations entre les mêmes entités restent autorisées.', source: MERISE_SOURCE },
  W009: { id: 'MERISE-W009', severity: 'warning', title: 'Clé étrangère possiblement saisie dans le MCD', category: 'normalization', certainty: 'heuristic', explanation: 'Une propriété ressemble à l’identifiant d’une entité déjà reliée par une association.', suggestion: 'Vérifiez qu’il ne s’agit pas d’une copie de clé étrangère : celle-ci est générée au passage au MLD. Conservez une référence métier distincte si nécessaire.', source: MERISE_SOURCE },
  W010: { id: 'MERISE-W010', severity: 'warning', title: 'Donnée calculée potentiellement redondante', category: 'normalization', certainty: 'heuristic', explanation: 'Cette propriété pourrait se calculer à partir d’autres propriétés du même objet.', suggestion: 'Documentez un instantané historique nécessaire ; sinon, calculez la valeur à la demande.', source: MERISE_SOURCE },
  W011: { id: 'MERISE-W011', severity: 'warning', title: 'Dépendance des propriétés d’association à vérifier', category: 'normalization', certainty: 'heuristic', explanation: 'Avec une participation de maximum 1, l’occurrence du lien est déterminée par cette entité seule.', suggestion: 'Vérifiez si les propriétés décrivent l’entité ou le lien. Ne les déplacez pas automatiquement, notamment pour une participation facultative.', source: ASSOCIATION_SOURCE },
  W012: { id: 'MERISE-W012', severity: 'warning', title: 'Clé fondée sur un nombre approché', category: 'normalization', certainty: 'heuristic', explanation: 'Un réel flottant n’est pas adapté à une comparaison métier exacte dans une clé.', suggestion: 'Préférez un identifiant stable, entier ou textuel ; utilisez un décimal exact si le domaine le nécessite.' },
  W013: { id: 'MERISE-W013', severity: 'warning', title: 'Domaine partiellement traduit en SQL', category: 'export', certainty: 'certain', explanation: 'Le SQL généré ne contraint pas toutes les options du type choisi.', suggestion: 'Ajoutez une contrainte CHECK adaptée au domaine dans le déploiement, ou choisissez un type dont le domaine est effectivement imposé.', source: SQL_SOURCE },
  W014: { id: 'MERISE-W014', severity: 'warning', title: 'Collection dans une propriété', category: 'normalization', certainty: 'heuristic', explanation: 'Un type tableau peut représenter plusieurs occurrences métier dans une seule propriété.', suggestion: 'Vérifiez l’atomicité au niveau métier et envisagez une entité liée si les éléments doivent être identifiés ou interrogés séparément.', source: MERISE_SOURCE },
  W015: { id: 'MERISE-W015', severity: 'warning', title: 'Propriété obligatoire d’un lien facultatif', category: 'export', certainty: 'certain', explanation: 'Une propriété NOT NULL du lien migre dans une table dont la participation est facultative : le SQL l’exige même sans lien.', suggestion: 'Adaptez le stockage du lien ou utilisez une contrainte conditionnelle pour que l’obligation dépende de l’existence du lien.', source: SQL_SOURCE },
  I001: { id: 'MERISE-I001', severity: 'info', title: 'Dépendances de la clé composée à documenter', category: 'normalization', certainty: 'manual', explanation: 'Une clé composée exige de vérifier que chaque propriété non clé dépend de la clé entière (2FN), puis l’absence de dépendance transitive (3FN).', suggestion: 'Documentez les dépendances fonctionnelles métier. Le diagramme seul ne permet pas de certifier 2FN, 3FN ou BCNF.', source: MERISE_SOURCE },
  I002: { id: 'MERISE-I002', severity: 'info', title: 'Participation minimale non garantie par le SQL', category: 'export', certainty: 'certain', explanation: 'L’export ne garantit pas l’existence d’un lien pour chaque occurrence du côté obligatoire indiqué.', suggestion: 'Prévoyez une règle transactionnelle ou un trigger différé ; une FK seule ne garantit pas la présence d’un enfant.', source: SQL_SOURCE },
  I003: { id: 'MERISE-I003', severity: 'info', title: 'Type libre à vérifier sur le serveur', category: 'export', certainty: 'manual', explanation: 'La syntaxe du type libre est vérifiée, mais pas son existence ni ses opérateurs sur le serveur PostgreSQL.', suggestion: 'Vérifiez les extensions, domaines, paramètres et opérateurs nécessaires, notamment si ce type sert de clé ou porte UNIQUE.' },
  I004: { id: 'MERISE-I004', severity: 'info', title: 'Entité isolée', category: 'model', certainty: 'manual', explanation: 'Cette entité n’est reliée à aucune association dans ce diagramme contenant plusieurs entités.', suggestion: 'Confirmez qu’il s’agit d’un référentiel indépendant et non d’une association oubliée.' },
} satisfies Record<string, RuleDefinition>
